title: My GitHub Page
description: Personal portfolio and projects

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Yolo on Raspberry Pi
    url: /yolo-on-raspberry-pi
  - title: Card Classification with PyTorch
    url: /fine-tuning-card-classification
  - title: Contact
    url: /contact
