title: My GitHub Page
description: Personal portfolio and projects

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

navigation:
  - title: Home
    url: /
  - title: Projects
    url: ./projects
  - title: Yolo on Raspberry Pi
    url: ./Project/Yolo on Rasberry Card
  - title: Card Classification with PyTorch
    url: ./Project/Classification With Pytorch
